# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 198)
        self.pushButton = QtWidgets.QPushButton(MainWindow)
        self.pushButton.setGeometry(QtCore.QRect(200, 160, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.clicked)
        self.PasswordInput = QtWidgets.QLineEdit(MainWindow)
        self.PasswordInput.setGeometry(QtCore.QRect(40, 110, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PasswordInput.setFont(font)
        self.PasswordInput.setStyleSheet("border-color: rgb(170, 0, 0);")
        self.PasswordInput.setInputMask("")
        self.PasswordInput.setText("")
        self.PasswordInput.setMaxLength(32767)
        self.PasswordInput.setFrame(False)
        self.PasswordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PasswordInput.setCursorPosition(0)
        self.PasswordInput.setObjectName("PasswordInput")
        self.UserInput = QtWidgets.QLineEdit(MainWindow)
        self.UserInput.setGeometry(QtCore.QRect(40, 60, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.UserInput.setFont(font)
        self.UserInput.setWhatsThis("")
        self.UserInput.setStyleSheet("border-color: rgb(170, 0, 0);")
        self.UserInput.setInputMask("")
        self.UserInput.setText("")
        self.UserInput.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.UserInput.setObjectName("UserInput")
        self.LoginLabel = QtWidgets.QLabel(MainWindow)
        self.LoginLabel.setGeometry(QtCore.QRect(60, 10, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LoginLabel.setFont(font)
        self.LoginLabel.setObjectName("LoginLabel")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def clicked(self):
        username = self.PasswordInput.text()
        password = self.PasswordInput.text()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dialog"))
        self.pushButton.setText(_translate("MainWindow", "Login"))
        self.PasswordInput.setPlaceholderText(
            _translate("MainWindow", "Password"))
        self.UserInput.setPlaceholderText(_translate("MainWindow", "Username"))
        self.LoginLabel.setText(_translate("MainWindow", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
