# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\kille\Documents\Programming\Python\IA\UIs\BlockList.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(280, 10, 291, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.BlockList = QtWidgets.QTableWidget(self.centralwidget)
        self.BlockList.setGeometry(QtCore.QRect(260, 120, 256, 381))
        self.BlockList.setObjectName("BlockList")
        self.BlockList.setColumnCount(1)
        self.BlockList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.BlockList.setHorizontalHeaderItem(0, item)
        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(30, 540, 101, 41))
        self.BackButton.setObjectName("BackButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "Blocked List"))
        item = self.BlockList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "List"))
        self.BackButton.setText(_translate("MainWindow", "Back"))
