# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\kille\Documents\Programming\Python\IA\UIs\IgnoreList.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(681, 520)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(240, 10, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.CopyText = QtWidgets.QLabel(self.centralwidget)
        self.CopyText.setGeometry(QtCore.QRect(110, 120, 491, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CopyText.setFont(font)
        self.CopyText.setObjectName("CopyText")
        self.InputName = QtWidgets.QLineEdit(self.centralwidget)
        self.InputName.setGeometry(QtCore.QRect(220, 230, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.InputName.setFont(font)
        self.InputName.setObjectName("InputName")
        self.Ignore = QtWidgets.QPushButton(self.centralwidget)
        self.Ignore.setGeometry(QtCore.QRect(530, 410, 111, 41))
        self.Ignore.setObjectName("Ignore")
        self.Unignore = QtWidgets.QPushButton(self.centralwidget)
        self.Unignore.setGeometry(QtCore.QRect(380, 410, 111, 41))
        self.Unignore.setObjectName("Unignore")
        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(20, 410, 111, 41))
        self.BackButton.setObjectName("BackButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 681, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "Ignore List"))
        self.CopyText.setText(_translate("MainWindow", "Copy/Paste Name from Main Screen to Ignore or Unignore "))
        self.InputName.setPlaceholderText(_translate("MainWindow", "Enter Name"))
        self.Ignore.setText(_translate("MainWindow", "Ignore"))
        self.Unignore.setText(_translate("MainWindow", "Unignore"))
        self.BackButton.setText(_translate("MainWindow", "Back"))
